services:
  - type: web
    name: parefrigeration-admin-dashboard
    env: node
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    buildCommand: npm install; npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
